# Generated by Django 5.0.6 on 2024-09-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
