# Generated by Django 5.0.6 on 2024-09-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lecture_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
