# Generated by Django 5.0.6 on 2024-09-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lecture_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='present',
            unique_together={('lecture', 'student')},
        ),
    ]
